# -*- coding: utf-8 -*-
"""pertemuan 3 PPM ACT-UB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kN-pyWkPwFlmHCtJzw0P9Rs6LvDxtylh
"""

# Import libraries
from sklearn.svm import SVC
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Load dataset Iris
data = load_iris()
X = data.data # Fitur (sepal length, sepal width, petal length, petal width)
y = data.target # Label (setosa, versicolor, virginica)

# 2. Split data menjadi training dan testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 3. Train SVM model dengan kernel RBF
model = SVC(kernel='rbf', C=1.0) # Kernel RBF dan C=1.0
model.fit(X_train, y_train)

# 4. Prediksi hasil pada data uji
y_pred = model.predict(X_test)

# 5. Evaluasi model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Output hasil evaluasi
print(f'Accuracy: {accuracy * 100:.2f}%')
print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)